### ISSUE TITLE
ButtonSetup widget missing in default skin

### ISSUE THREAD

**Issue by biot** [OpenViX/skins#62]
In a 5.3.028.003 image I get a crash when trying to enter the Button setup menu item:

  Error in screen 'ButtonSetup' widget 'widget' [Skin] {ViX-Night-HD/skin.xml}: Com
ponent with name 'config' was not found in skin of screen 'ButtonSetup'!  Please contact the skin's author!!

[Enigma2_crash_2020-05-12_20-27-26.log](https://github.com/OpenViX/skins/files/4625085/Enigma2_crash_2020-05-12_20-27-26.log)

**Comment by AbuBaniaz** [comment]
It is not a skin issue. I made a mistake with the action cpp files. A new build is on its way.

Thanks for reporting

**Comment by RobvanderDoes** [comment]
So we can close this report?
