### ISSUE TITLE
skin_YouViX_Templates.xml

### ISSUE THREAD

**Issue by Orlandoxx** [OpenViX/skins#72]
There is an error on skin file : skin_YouViX_Templates.xml: 'Youyou' must be changed to 'You'.

**Comment by Huevos** [comment]
Please change as required.

**Comment by AbuBaniaz** [comment]
Thanks.  Done here
https://github.com/OpenViX/skins/commit/583fd3e468548157f7b11d74ac6eabfd2a61ac55
